name: pre-commit

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  run:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
            build-essential \
            clang \
            clang-tidy \
            cmake

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pre-commit
        run: pre-commit run --all-files
