name: Visual Studio Build

on:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure CMake (Visual Studio)
        run: cmake -S . -B build -G "Visual Studio 17 2022"

      - name: Build solution
        run: cmake --build build --config Release
